### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ifucolo/Android-Smart-Custom-Calendar#1]
I get this issue:

![image](https://user-images.githubusercontent.com/5357526/31931403-cc6d323c-b8ab-11e7-97df-350689f0d83f.png)

**Comment by ifucolo** [comment]
if you remove this can be work, I will do a update for kotlin on next weeks

**Comment by AndroidDeveloperLB** [comment]
Remove what?

**Comment by rdperinazzo** [comment]
Gostei do seu trabalho... estou iniciando no android e queria usar seu Custom calendar para incrementar uma escala de plantão para o meu serviço, como que eu colocaria um círculo ou um ponto para cada dia do trabalho? Por exemplo dia 1/5/2018 Equipe 2, 2/5 Equipe 3, 3/5 Equipe 4, 4/5 Equipe 5, 5/5 Equipe 1, são 5 equipes de revezamento.  Se você puder me ajudar agradeço.  Rogerio Denis Perinazzo.

**Comment by AndroidDeveloperLB** [comment]
I don't understand

**Comment by ifucolo** [comment]
@AndroidDeveloperLB you can not run because there is only classes, you need just copy the classes for your project

**Comment by AndroidDeveloperLB** [comment]
@ifucolo What classes? And to where? And why?
Why can't I just try out the repository?

**Comment by ifucolo** [comment]
@AndroidDeveloperLB I will update the repository for you can run, just a moment

**Comment by ifucolo** [comment]
@rdperinazzo vou fazer um update e já te explico como tu pode fazer

**Comment by AndroidDeveloperLB** [comment]
@ifucolo Thank you.
I don't understand the other language text though.

**Comment by ifucolo** [comment]
@AndroidDeveloperLB right now you can clone again and build

**Comment by AndroidDeveloperLB** [comment]
Yes it works fine now.
Thank you
